title: Jamie Grantham-Burton
email: jgranthamburton@gmail.com
description:  # this means to ignore newlines until "baseurl:"
  <p class="subtitle">I’m a Web Developer and Jazz Musician based in London, UK.</p>
  <br>
  <p class="subtitle">University of Huddersfield BA Music Alumni | General Assembly WDI Alumni</p>
  <br>
  <p class="subtitle">HTML | CSS3/Bootstrap | Javascript | Wordpress | PHP | Git</p>
# permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jgranthamburton.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Jamie Grantham-Burton # add your name
author-pic: jamie.jpg
about-author: <p class="subtitle">I’m a Web Developer and Jazz Musician based in London, UK.</p>
<br>
<p class="subtitle">University of Huddersfield BA Music Alumni | General Assembly WDI Alumni</p>
<br>
<p class="subtitle">HTML | CSS3/Bootstrap | Javascript | Wordpress | PHP | Git</p>

# Contact links
# email: jgranthamburton@gmail.com
# phone: # Add your Phone number
# website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: jgburton # Add your Github handle
twitter: '@jgranthamburton' # Add your Twitter handle
# facebook: # Add your Facebook handle
instagram: jgranthamburton
# pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
